# Wire up travis
language: python
sudo : false

matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true
      env: TOXENV=py37

env:
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=py36
  - TOXENV=pypy
  - TOXENV=pypy3
  - TOXENV=coverage

install:
  - travis_retry pip install tox

script:
  - travis_retry tox

notifications:
  email:
    - repoze-checkins@lists.repoze.org
